import { CarouselConfig } from '../types/tmdb'

// genreKey values map to GENRE_KEY_MAP in src/utils/genreKeyMap.ts
// Carousels without genreKey are "generic" and always visible regardless of category filter.
export const CAROUSEL_CONFIG: CarouselConfig[] = [
  { id: 'new-movies',          type: 'movies', hookKey: 'newReleases',              rankDisplay: false },
  { id: 'new-shows',           type: 'shows',  hookKey: 'newShows',                 rankDisplay: false },
  { id: 'daily-top10-movies',  type: 'movies', hookKey: 'dailyTrending',            rankDisplay: true  },
  { id: 'daily-top10-shows',   type: 'shows',  hookKey: 'tvDailyTrending',          rankDisplay: true  },
  { id: 'weekly-top10-movies', type: 'movies', hookKey: 'weeklyTrending',           rankDisplay: true  },
  { id: 'weekly-top10-shows',  type: 'shows',  hookKey: 'tvWeeklyTrending',         rankDisplay: true  },
  { id: 'recommended-movies',  type: 'movies', hookKey: 'trending',                 rankDisplay: false },
  { id: 'recommended-shows',   type: 'shows',  hookKey: 'recommendedShows',         rankDisplay: false },
  { id: 'acclaimed-movies',    type: 'movies', hookKey: 'acclaimed',                rankDisplay: false },
  { id: 'acclaimed-shows',     type: 'shows',  hookKey: 'criticallyAcclaimedShows', rankDisplay: false },
  { id: 'comedy-movies',       type: 'movies', hookKey: 'comedy',                   rankDisplay: false, genreKey: 'comedy'     },
  { id: 'comedy-shows',        type: 'shows',  hookKey: 'comedyShows',              rankDisplay: false, genreKey: 'comedy'     },
  { id: 'scifi-movies',        type: 'movies', hookKey: 'sciFiFantasy',             rankDisplay: false, genreKey: 'scifi'      },
  { id: 'scifi-shows',         type: 'shows',  hookKey: 'sciFiFantasyShows',        rankDisplay: false, genreKey: 'scifi'      },
  { id: 'reallife-movies',     type: 'movies', hookKey: 'realLife',                 rankDisplay: false, genreKey: 'documentary'},
  { id: 'reallife-shows',      type: 'shows',  hookKey: 'realLifeShows',            rankDisplay: false, genreKey: 'documentary'},
  { id: 'animation-movies',    type: 'movies', hookKey: 'animation',                rankDisplay: false, genreKey: 'animation'  },
  { id: 'animation-shows',     type: 'shows',  hookKey: 'animationShows',           rankDisplay: false, genreKey: 'animation'  },
  { id: 'romance-movies',      type: 'movies', hookKey: 'romance',                  rankDisplay: false, genreKey: 'romance'    },
  { id: 'romance-shows',       type: 'shows',  hookKey: 'romanceShows',             rankDisplay: false, genreKey: 'romance'    },
  { id: 'action-movies',       type: 'movies', hookKey: 'actionAdventure',          rankDisplay: false, genreKey: 'action'     },
  { id: 'action-shows',        type: 'shows',  hookKey: 'actionAdventureShows',     rankDisplay: false, genreKey: 'action'     },
  { id: 'award-movies',        type: 'movies', hookKey: 'awardWinning',             rankDisplay: false, genreKey: 'drama'      },
  { id: 'award-shows',         type: 'shows',  hookKey: 'awardWinningShows',        rankDisplay: false, genreKey: 'drama'      },
  { id: 'inspiring-movies',    type: 'movies', hookKey: 'inspiring',                rankDisplay: false, genreKey: 'drama'      },
  { id: 'inspiring-shows',     type: 'shows',  hookKey: 'inspiringShows',           rankDisplay: false, genreKey: 'drama'      },
  { id: 'thriller-movies',     type: 'movies', hookKey: 'thriller',                 rankDisplay: false, genreKey: 'thriller'   },
  { id: 'thriller-shows',      type: 'shows',  hookKey: 'thrillerShows',            rankDisplay: false, genreKey: 'thriller'   },
  { id: 'upcoming-movies',     type: 'movies', hookKey: 'upcomingMovies',           rankDisplay: false },
  { id: 'upcoming-shows',      type: 'shows',  hookKey: 'upcomingShows',            rankDisplay: false },
]
